### ISSUE TITLE
1.8.3 – Potentially unhandled rejection [2] Error: no writecb in Transform class

### ISSUE THREAD

**Issue by volkish** [tracker1/gulp-header#41] opened 2016-06-20 09:15 UTC
Task:
`gulp.task('components_styles', function () {
	gulp.src(paths.components.styles)
		.pipe(less({
			paths: [
				'./public_html/static/assets/stylesheets'
			]
		}))
		.pipe(csso())
		.pipe(header(fileHeaders))
		.pipe(rename(fixComponentPath))
		.pipe(gulp.dest('./public_html/static/assets/stylesheets/Components'));
});`

**Comment by gtanner** [comment] 2016-06-20 20:28
Encountered this as well, pinned our dep to 1.7.1 for now while we wait for this to be fixed.

**Comment by alessandrovaccaro** [comment] 2016-06-21 09:31
Is this issue potentially be the cause of this [one](https://github.com/swagger-api/swagger-ui/issues/2227) on swagger-ui?

**Comment by tracker1** [comment] 2016-06-21 17:45
is this still happening with 1.8.4?  I pushed the patch wrt the pending pull request...

**Comment by tracker1** [comment] 2016-06-21 18:12
Should be fixed in 1.8.4/5

**Closed by tracker1** 2016-06-21 18:12 UTC

**Comment by alessandrovaccaro** [comment] 2016-06-21 18:14
@tracker1 I have tried it on swagger-ui and it looks good, thank you!

**Comment by tracker1** [comment] 2016-06-21 19:21
see #44
